version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
  web:
    build: .
    ports:
      - "2111:2111"
    environment:
      - MONGO_URL=mongodb://db:27017/mydatabase
      - ACCESS_TOKEN_SECRET=0904195777@
      - REFRESH_TOKEN_SECRET=LEVANMONG-0904195-1999-21-11-11
      - REFRESH_TOKEN_LIFE=604800000
    depends_on:
      - db
  db:
    image: mongo
